//
//  YSDrawablesStyleKit.h
//  YSDrawables
//
//  Created by Alexander Yianni on 19/11/2015.
//  Copyright (c) 2015 Yianni Software Pty Ltd. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface YSDrawablesStyleKit : NSObject

// Drawing Methods
+ (void)drawStarWithFrame: (CGRect)frame fillColor: (UIColor*)fillColor;
+ (void)drawCircleWithFrame: (CGRect)frame fillColor: (UIColor*)fillColor;
+ (void)drawHexagonWithFrame: (CGRect)frame fillColor: (UIColor*)fillColor;
+ (void)drawLightningWithFrame: (CGRect)frame fillColor: (UIColor*)fillColor strokeColor: (UIColor*)strokeColor;

@end
